### ISSUE TITLE
Combat macros sending

### ISSUE THREAD

**Issue by Renniol** [Lumenita/abfalter#10]
![image](https://github.com/Lumenita/abfalter/assets/171416300/4f6c71ae-d1b7-4e9c-91a9-994f2664a4dc)
![image](https://github.com/Lumenita/abfalter/assets/171416300/f2e3d149-a533-4459-b3c7-d84ecc2c6953)
![image](https://github.com/Lumenita/abfalter/assets/171416300/ea68c1fd-59d7-4b67-874f-80f7884b9f92)
![image](https://github.com/Lumenita/abfalter/assets/171416300/99d282ff-652c-4f22-84bd-e6308844c3ee)
![image](https://github.com/Lumenita/abfalter/assets/171416300/07a0ff8a-19f2-4cf2-97b5-6a1a52086e68)

and nothing happend v11/315 ftt
Maybe I'm doing something wrong? After selecting an attack and clicking send attack, nothing is displayed anywhere, I tried it only from the host’s side and through the browser in several windows as different players. I apologize for writing through errors, I just didn’t find where I can write to you directly on these issues.
I also wanted to ask if you would be against including the Russian language if I make a language json file?

**Comment by Lumenita** [comment]
The combat calculator does not work right, its under development, but also its development is paused as I polish out everything else.

Yes, I'd be happy to include the Russian json if I received one!

**Comment by Renniol** [comment]
[ru.json](https://github.com/user-attachments/files/15588813/ru.json)
I tried to compress the texts as much as possible, but in some cases this is either simply unrealistic due to the language design, or, for example, in the Shefira arcana, there the hidden window for the text simply does not correspond to the Russian name.

**Comment by Lumenita** [comment]
Thank you!
That's understandable with the issues of text compression, at least you should be able to exapnd the window to be wider which should let it fit.
I just released an update without checking this first (apologies), I'll include it in the next update which should be next week!
