### ISSUE TITLE
Seals of the Dragon do not modify the correct stats, or derived stats

### ISSUE THREAD

**Issue by Jetshelby** [Lumenita/abfalter#4]
![image](https://github.com/Lumenita/abfalter/assets/131572100/ae0cac37-cda8-4d22-82b2-c50aec99f089)

Seals of the dragon should modify all physical stats, and power. Currently, it does not seem to be recalculating all derived stats.

![image](https://github.com/Lumenita/abfalter/assets/131572100/8d1ec42e-ab37-44d9-9d29-6cd6e7466e5d)

Max health should increase, as should fatigue, and so on.

**Comment by Jetshelby** [comment]
The test is being done with 4 seals, and 2 Doors of the dragon open.

**Comment by Lumenita** [comment]
Thank you for reporting this issue,
Dragon seals now properly affect derived data in v1.1.0
If there are no other issues, please close this issue
