### ISSUE TITLE
Running speed is improperly calculated

### ISSUE THREAD

**Issue by Jetshelby** [Lumenita/abfalter#5]
It is set to half-max speed. The book says running speed is Speed - 2.

Perhaps you meant this for Marching speed? The book provides no recommendation for Marching speed it seems.

![image](https://github.com/Lumenita/abfalter/assets/131572100/79ec915d-9e0d-4f3b-b88b-948b32b6f41d)

**Comment by Lumenita** [comment]
Thank you for reporting this issue,
Running speed should be calculated properly now in v1.1.0
For movement values 1,2,3 & 17,18,19 I left it as max movement / 2 just so its higher than the 1/4
If there are no other issues, please close this issue
